### ISSUE TITLE
[Task Card] Open API 데이터 수집 및 출력  (방법 1.)

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/labQ-Wanted-A#10]
### **ISSUE**

- Group: `A Team`
- Type: `feature`
- Detail: Open API 데이터 수집 및 출력

### **TODO**

- [x] 서울 하수관로 수위 현황 Open API 데이터 수집하기
- [x] 서울시 강우량 정보 Open API 데이터 수집하기
- [x] 수집한 두 데이터를 이용하여 병렬적으로 결합하기

### **Labels**

- Estimated time: `E: 2h`
- Group : `A Team`
- Urgency: `High`
