### ISSUE TITLE
[Task Card] Open API 데이터 수집 및 전처리, 출력 (방법 2.)

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/labQ-Wanted-A#13]
### **ISSUE**

- Group: `A Team`
- Type: `feature`
- Detail: Open API 데이터 수집 및 출력

### **TODO**

- [x] 서울 하수관로 수위 현황 Open API 데이터 수집하기
- [x] 서울 하수관로 수위 현황 지역별 코드에 맞게 평균값 처리하기 (데이터 전처리)
- [x] 서울시 강우량 정보 Open API 데이터 수집하기
- [x] 수집한 두 데이터를 결합하여 출력하기

### **Labels**

- Estimated time: `E: 3h`
- Group : `A Team`
- Urgency: `High`
