### ISSUE TITLE
[Task Card] 초기 세팅

### ISSUE THREAD

**Issue by dltmddus1998** [3rd-wanted-pre-onboarding-teamA/labQ-Wanted-A#8]
### **ISSUE**

- Group: `A Team`
- Type: `setting`
- Detail: 초기 세팅

### **TODO**

- [x] npm, node ver. 확인
- [x] 필요한 모듈 설치 (package.json)
- [x] 통신 설정 및 확인 

### **Labels**

- Estimated time: `E: 2h`
- Group : `A team`
- Urgency: `High`
